

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./code:/code
            - ./php.ini:/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
        networks:
            - code-network

networks:
    code-network:
        driver: bridge